### ISSUE TITLE
tabulate VCO circuits control voltage vs frequency

### ISSUE THREAD

**Issue by NishchalAV** [NishchalAV/Phase-locked-loop_VLSI#7]

**Comment by NishchalAV** [comment]
https://docs.google.com/document/d/1sm7zU_pfag36Yeht2N0TDySxm_cB71H6/edit?usp=sharing&ouid=105332818258497235015&rtpof=true&sd=true

**Comment by suryal30103** [comment]
![Image](https://github.com/NishchalAV/Phase-locked-loop_VLSI/assets/128246519/275aa28e-ba51-47dc-b22f-691bf21ee9f9)

For 5 stage VCO
